// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetTheme(arg1) {
  return window['go']['main']['App']['GetTheme'](arg1);
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function GetTerminalWSInfo() {
  return window['go']['main']['App']['GetTerminalWSInfo']();
}

export function CreateTerminalSession(arg1) {
  return window['go']['main']['App']['CreateTerminalSession'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}
