// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig(): Promise<any>;
export function GetTheme(name: string): Promise<any>;
export function ListThemes(): Promise<string[]>;
export function GetTerminalWSInfo(): Promise<{ port: number; token: string }>;
export function CreateTerminalSession(id: string): Promise<void>;
export function ResizeTerminal(id: string, cols: number, rows: number): Promise<void>;
export function CloseTerminalSession(id: string): Promise<void>;
